package org.docear.metadata.adapter;

import org.docear.metadata.data.MetaDataSource;
import org.docear.metadata.data.ScholarMetaData;
import org.docear.metadata.io.Metadata2BibtexConverter;
import org.docear.metadata.model.BibliographicMetadata;

/**
 * Result carrier of the new metadata providers.
 *
 * It extends ScholarMetaData so the existing downstream chain
 * (MetaDataExtractorPage: "result instanceof ScholarMetaData" ->
 * BibtexParser.parse(getBibtex()) -> BibtexEntry) keeps working without any
 * modification: the bibtex string is generated by
 * Metadata2BibtexConverter, and the structured model is additionally carried
 * along for scoring/deduplication purposes.
 *
 * New code of the metadata provider extension (phase 1: Crossref). Java 1.6
 * syntax only.
 */
public class BibMetaData extends ScholarMetaData {

	private static final long serialVersionUID = 1L;

	private final BibliographicMetadata structured;
	private final String providerName;

	public BibMetaData(int rank, BibliographicMetadata metadata, String providerName, MetaDataSource source,
			String query) {
		super(rank, "", query);
		setSource(source);
		this.structured = metadata;
		this.providerName = providerName;
		setBibtex(Metadata2BibtexConverter.toBibtex(metadata));
	}

	/** The structured view of the same data that is flattened into the bibtex. */
	public BibliographicMetadata getStructured() {
		return structured;
	}

	public String getProviderName() {
		return providerName;
	}
}
